apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurestorage-test
spec:  
  selector:
      matchLabels:
        app: azurestorage-test
  template:
    metadata:
      labels:
        app: azurestorage-test
    spec:
      containers:
      - name: azurestorage-test
        image: {ACR_LOGIN_SERVER}/node-app:latest
        volumeMounts:
          - name: azure
            mountPath: /var/azurefileshare
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: aksshare
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: azurestorage-test
  labels:
    name: azurestorage-test
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: azurestorage-test
  type: LoadBalancer
